name: tesla_owner_api
description: Unleash the power of your Tesla products with the Tesla Owner API package. Interact with vehicles, Powerwalls, energy sites, and more. Ideal for Tesla owners and enthusiasts.
version: 1.0.0
homepage: https://github.com/PlaxXOnline/tesla_owner_api
issue_tracker: https://github.com/PlaxXOnline/tesla_owner_api/issues

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.2.1+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

